## 1. NumPy 기초

In [121]:
import numpy as np
a = np.arange(9).reshape(3,3)
a

a_reshaped = a
a_flatten = a
a_ravel = a

print(a_reshaped)
a_reshaped.reshape(-1,1)  # 1차원으로 변경 -> 원본에 영향을 미침
print(a_reshaped)
print(a_flatten)
a_flatten.flatten()  # 1차원으로 변경-> 원본과 별개로 구분됨
print(a_flatten)
print(a_ravel)
a_ravel.ravel()  # 1차원으로 변경 -> 원본에 영향을 미침
print(a_ravel)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [124]:
a = np.arange(9).reshape(3,3)
a
a[1:3,:]
b = a[1:3,:]
b[0] = 100
print(b)
print(a)

[[100 100 100]
 [  6   7   8]]
[[  0   1   2]
 [100 100 100]
 [  6   7   8]]


In [126]:
a = np.array([2,4,6,8])
print(a)
idx = np.array([0,0,0,0,1,1,2,2])  # 인덱스값을 반복해서 나열하고, 이를 인덱스로 하는 넘파이 배열 출력
a[idx]

[2 4 6 8]


array([2, 2, 2, 2, 4, 4, 6, 6])

In [120]:
a = np.array([1, 3, 2, 5, 7])
s = a.argsort()  # argmax, argmin (index 값 반환)
print(a[s])
print(a)
print(s)

[1 2 3 5 7]
[1 3 2 5 7]
[0 2 1 3 4]


In [117]:
print(s[::-1])

[4 3 1 2 0]


In [ ]:
# ndarray 생성; 
import numpy as np
np.array()

In [1]:
import numpy as np
arr = np.array([[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [2]:
arr[[0,1,2], [0,1,0]]

array([1, 4, 5])

In [55]:
a = np.array([1,3,4])
print(a)

[1 3 4]


> 다시

In [4]:
np.insert(a,[1,2])

TypeError: _insert_dispatcher() missing 1 required positional argument: 'values'

In [56]:
np.insert(a,1,[1,2])

array([1, 1, 2, 3, 4])

In [5]:
np.insert(a,1,2)

array([1, 2, 3, 4])

In [9]:
arr = np.array([0,2,0,1])
arr

array([0, 2, 0, 1])

> 다시

In [35]:
arr = np.arange(4)
print(arr)

[0 1 2 3]


In [36]:
arr = np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

----

In [16]:
import numpy as np
arr2 =np.array([0,2,0,1])
arr = np.arange(4),arr2
arr

(array([0, 1, 2, 3]), array([0, 2, 0, 1]))

In [38]:
arr = np.arange(1,13).reshape(4,3)
arr
arr2 = np.array([0,2,0,1])
arr[np.arange(4),arr2]

array([ 1,  6,  7, 11])

In [17]:
arr[[0,1,2,3], [0,2,0,1]]

TypeError: tuple indices must be integers or slices, not tuple

In [11]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [12]:
print(np.sum(x))

10


In [13]:
print(np.sum(x, axis=0))

[4 6]


> 다시

In [19]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [144]:
print(zip(xarr, yarr, cond))

In [20]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [21]:
result2 = np.where(cond, xarr, yarr)
print(result2)

[1.1 2.2 1.3 1.4 2.5]


In [22]:
arr = np.random.randn(4,4)
print(arr)

[[ 4.94087469e-01 -6.24606759e-01  4.88635842e-01 -1.10146876e+00]
 [-5.71896958e-04  1.36108914e+00 -6.89319795e-01 -9.48761261e-01]
 [-3.68877980e+00 -1.47741610e+00  2.94160551e-01  1.39162320e-01]
 [ 1.27093287e+00 -8.32955483e-01  4.02747464e-01 -5.01625664e-01]]


In [23]:
print(np.where(arr>0, 1, -1))

[[ 1 -1  1 -1]
 [-1  1 -1 -1]
 [-1 -1  1  1]
 [ 1 -1  1 -1]]


In [24]:
samples = np.random.normal(size=(4,4))
print(samples)

[[ 1.54644325 -2.06457389 -1.65242081  0.2400037 ]
 [ 1.24784236  2.56625833  2.75786863  0.98087965]
 [ 0.20460479  0.67565025  0.04736907  1.81349099]
 [ 1.45784745 -0.50605574 -0.41916593  1.11568327]]


> 코드 실행 시간 확인

In [41]:
from random import normalvariate
N = 1000000

In [42]:
%timeit samples = [normalvariate(0,1) for _ in range(N)]

747 ms ± 15.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [43]:
%timeit np.random.normal(size=N)

25 ms ± 325 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


문제 1

In [26]:
n = int(input('n을 입력하시오: '))

x = np.eye(n)
print(x)

n을 입력하시오:  5


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---

다시

In [115]:
n = int(input('n을 입력하시오: '))
a = np.eye(n, dtype = 'int32')
b = np.flip(a, axis = 1)
c = a + b
if len(c) % 2 == 1:
    c[int(len(c)/2), int(len(c)/2)] = 1
    print(int(len(c))/2)
    print(len(c))
    print(c[int(len(c)/2), int(len(c)/2)])

print(c)

n을 입력하시오:  5


2.5
5
1
[[1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]]


In [27]:
n = int(input('n을 입력하시오: '))

x = np.eye(n)
print(x)

n을 입력하시오:  6


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [44]:
n = int(input('n을 입력하시오: '))
a = np.eye(n, dtype = 'int32')
b = np.flip(a, axis = 1)
c = a + b
if len(c) % 2 == 1:
    c[int(len(c)/2), int(len(c)/2)] = 1

print(c)

n을 입력하시오:  6


[[1 0 0 0 0 1]
 [0 1 0 0 1 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]
 [0 1 0 0 1 0]
 [1 0 0 0 0 1]]


> 다시

In [45]:
n = int(input('n을 입력하시오: '))
a = np.eye(n, dtype = 'int32')
b = np.flip(a, axis = 1)
c = a + b
if len(c) // 3 == 2:
    c[int(len(c)/2), int(len(c)/2)] = 1

print(c)

n을 입력하시오:  5


[[1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 2 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]]


In [52]:
c = a.sum(axis=1)
print(c)

[ 3 12  6 24]


In [47]:
# numpy의 append함수를 이용한 구현방법
a = np.array([[0,1,2], [3,4,5], [0,2,4], [6,8,10]])
print('a =', a)

a1 = np.append(a[0], a[2])
a2 = np.append(a[1], a[3])
b = np.array([a1, a1])
print('b =', b)

a = [[ 0  1  2]
 [ 3  4  5]
 [ 0  2  4]
 [ 6  8 10]]
b = [[0 1 2 0 2 4]
 [0 1 2 0 2 4]]


- concatenate() 함수

In [48]:
np.concatenate((a1, a2))

array([ 0,  1,  2,  0,  2,  4,  3,  4,  5,  6,  8, 10])

> 둘의 차이; 없음 (np.concatenate에서는 모두 array로 뱉어냄)

In [51]:
a1 = np.concatenate([a[0], a[2]])
a1

array([0, 1, 2, 0, 2, 4])

In [53]:
np.concatenate((a[0], a[2]))

array([0, 1, 2, 0, 2, 4])

문제 2

In [59]:
a = np.full((5, 5), 0)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [63]:
np.diag(np.diag(a))

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
for i in a:
    diag

In [75]:
c = a[:3,:3]
c

array([[0, 0, 0],
       [0, 1, 1],
       [0, 1, 2]])

----

In [76]:
import numpy as np
n = 5
a = np.ones((n,n), dtype = 'int32')
a[0, :] = a[-1, :] = a[:, 0] = a[:, -1] = 0
a[2, 2] = 2
print('배열 a:')
print(a)

배열 a:
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 2 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [77]:
b = a[1:-1, 1:-1]
print('1) 배열 b: ')
print(b)

1) 배열 b: 
[[1 1 1]
 [1 2 1]
 [1 1 1]]


In [91]:
c = a[0:-2, 0:-2]
print('2) 배열 c: ')
print(c)

2) 배열 c: 
[[[0 1]]

 [[6 7]]]


In [79]:
d = a[0:-2, 1:-1]
print('3) 배열 d: ')
print(d)

3) 배열 d: 
[[0 0 0]
 [1 1 1]
 [1 2 1]]


In [80]:
e = a[1:-1, 2:]
print('4) 배열 e: ')
print(e)

4) 배열 e: 
[[1 1 0]
 [2 1 0]
 [1 1 0]]


In [81]:
f = a[:, 2]
print('5) 배열 f: ')
print(f)

5) 배열 f: 
[0 1 2 1 0]


문제 3 특정 위치에 있는 원소값 구하기

In [82]:
a = np.arange(0, 24).reshape(4, 3, 2)

In [90]:
## a차원의 값을 튜플 형태로 받아줌; 몇 행 몇 열의 값으로 받아줬으므로 출력해야함
a.shape[0], a.shape[1], a.shape[2]

(4, 3, 2)

In [83]:
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [88]:
a[3][2]

array([22, 23])

---

In [99]:
def get_nth(n,a):
    # 10번째 원소를 구하기 위해 n-1 필요
    n = n - 1
    # n을 a.shape의 마지막 값(열의 갯수)로 나누고 나머지를 구함
    ix_2 = n % a.shape[2]
    helper_2 = (n - ix_2) / a.shape[2]
    ix_1 = helper_2 % a.shape[1]
    helper_1 = (helper_2 - ix_1) / a.shape[1]
    ix_0 = helper_1 % a.shape[0]
    # print(int(ix_0), int(ix_1), int(ix_2))
    return a[int(ix_0), int(ix_1), int(ix_2)]
        
n = 10
print('a 행렬의 {}번째 원소: {}'.format(n,a))
n = 20
print('a 행렬의 {}번째 원소: {}'.format(n,a))

a 행렬의 10번째 원소: [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
a 행렬의 20번째 원소: [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


### 날짜와 시간 처리 함수

In [97]:
from datetime import datetime, timedelta, timezone

import pytz
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as dates

In [98]:
# timezone unawared datetime
datetime(2019,1,1)

datetime.datetime(2019, 1, 1, 0, 0)

In [102]:
datetime(2019,1,1,tzinfo=datetime)

TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'type'

In [103]:
KST = pytz.timezone('Asia/Seoul')

In [104]:
print(KST)

Asia/Seoul


In [ ]:
KST.localize(mydate)

In [ ]:
# strftime.org 참조
mydate_kst.strftime("%Y-%m-%d %H:%M:%S%Z")

In [ ]:
mydate_kst.astimezone(pytz.utc).strftimme("%Y-%m-%d %H:%M:%S%Z")  # KST를 영국의 그리니치 시간으로 변환

In [105]:
# datetime 라이브러리, timedelta: 시간 간 차이를 구하는 클래스
import datetime as dt
dt1 = dt.datetime(2017, 1, 31, 13, 26, 20, 123456)  # microsecond 포함
date1 = dt.date(2017, 1, 31)
time1 = dt.time(13, 26, 20, 123456)

In [106]:
print(dt1.year, dt1.month, dt1.day,
      dt1.hour, dt1.minute, dt1.second, dt1.microsecond, dt1.tzinfo)

2017 1 31 13 26 20 123456 None


In [ ]:
td = today - seoul_dt1
print(type(td))
print(td)

In [ ]:
print(today.tzinfo)
print(shanghai_dt1.tzinfo)
print(today - shanghai_dt1

In [107]:
import datetime as dt
tday = dt.date.today()
print(tday)
print(type(tday))

2022-08-11
<class 'datetime.date'>


In [108]:
today = datetime.today()
print(today)

2022-08-11 12:12:32.804345


In [ ]:
today = 

In [109]:
datetime.today().astimezone(KST)

datetime.datetime(2022, 8, 11, 12, 13, 46, 176536, tzinfo=<DstTzInfo 'Asia/Seoul' KST+9:00:00 STD>)

- 최근 금요일 날짜 리턴하는 함수 만들기

In [110]:
# 요일 가져오기
datetime(2019,1,23).weekday()

2

In [111]:
# UTC 시간과 KST 시간 차이는 9시간
pytz.utc.localize(mydate) - KST.localize(mydate)

NameError: name 'mydate' is not defined

In [ ]:
timedelta(second)

In [ ]:
isoweekday()

### 2. Pandas

- 이종 자료형의 열을 가진 테이블 데이터
- 시계열 데이터
- 레이블을 가진 다양한 행렬 데이터
- 다양한 관측 통계 데이터

- 시리즈: 1차원 구조를 가진 하나의 열 (동일한 데이터 타입으로 구성돼있어야 함)
- 데이터프레임: 복수의 열을 가진 2차원 데이터 (R의 dataframe 모방; 숫자&문자 등 다양한 데이터를 하나의 테이블에 담을 수 있음)

판다스는 panel data라는 용어에서 유래된 계량경제학 용어로, 동일한 관찰자에 의하여 여러 회에 걸쳐서 관측된 데이터의 집합을 의미함

- list, dictionary, numpy

- NumPy의 모두 같은 자료값을 가지는 단순한 수치 정보 중심으로만 구성돼있다는 한계를 보완해주는 것이 Pandas


In [127]:
import pandas as pd
import numpy as np

se = pd.Series([1, 2, np.nan, 4])
se

0    1.0
1    2.0
2    NaN
3    4.0
dtype: float64

- 결측치가 있는지를 boolean으로 반환하는 함수는 isna()

In [128]:
se.isna()

0    False
1    False
2     True
3    False
dtype: bool

> 각 데이터를 Series로 변환하고, 데이터의 feature별로 결측치의 유무 및 비율 파악

In [130]:
se[0], se[1]  # 시리즈의 자료구조도 동일하게 리스트 인덱싱 방법 사용

(1.0, 2.0)

In [132]:
print(se)

0    1.0
1    2.0
2    NaN
3    4.0
dtype: float64


In [131]:
data = se
indexed_se = pd.Series(data, index = ['a', 'b', 'c', 'd'])
print(indexed_se)

a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64


In [133]:
data = se
indexed_se = pd.Series(se, index = ['a', 'b', 'c', 'd'])
print(indexed_se)

a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64


In [134]:
indexed_se['a'], indexed_se['b']

(nan, nan)

In [135]:
income = {'1월': 9500, '2월': 6200, '3월': 6050, '4월': 7000}
income_se = pd.Series(income)
print('동윤이네 상점의 수익')
print(income_se)

동윤이네 상점의 수익
1월    9500
2월    6200
3월    6050
4월    7000
dtype: int64


In [138]:
myseries = pd.Series(range(0,4))
myseries

0    0
1    1
2    2
3    3
dtype: int64

In [139]:
k1 = pd.Series([100, 101, 102, 103, 104, 105], index = ['2018-11-01', '2018-11-02', '2018-11-03', '2018-11-04', '2018-11-05', '2018-11-06'])
print(k1)        

2018-11-01    100
2018-11-02    101
2018-11-03    102
2018-11-04    103
2018-11-05    104
2018-11-06    105
dtype: int64


In [140]:
for date in k1.index:
    print(date)

for money in k1.values:
    print(money)

2018-11-01
2018-11-02
2018-11-03
2018-11-04
2018-11-05
2018-11-06
100
101
102
103
104
105


- 인덱스가 달라도 연산이 가능함 (Series의 브로드캐스트 기능)

In [141]:
mine = pd.Series([10,20,30], index = ['korean', 'english', 'math'])
friend = pd.Series([70,50,50], index = ['korean', 'math', 'english'])
merge = mine + friend
print(merge)

english    70
korean     80
math       80
dtype: int64


In [142]:
mine = pd.Series([10,20,30], index = ['english', 'korean', 'math'])
friend = pd.Series([70,50,50], index = ['korean', 'math', 'english'])
merge = mine + friend
print(merge)

english    60
korean     90
math       80
dtype: int64


In [145]:
# zip() 함수
numbers = [1, 2, 3]
letters = ["A", "B", "C"]
for i in range(3):
    pair = (numbers[i], letters[i])
    print(pair)

(1, 'A')
(2, 'B')
(3, 'C')


- 데이터프레임은 다양한 데이터 타입 (ndarray, dictionary, dataframe, series, list)으로 생성 가능

> 넘파이 배열을 데이터프레임으로 변환한 경우

In [146]:
import numpy as np
import pandas as pd

nparray1 = np.array([[1,2,3], [4,5,6]])
display(pd.DataFrame(nparray1))

0  1  2
0  1  2  3
1  4  5  6

> 딕셔너리를 데이터프레임으로 변환한 경우

In [147]:
dictionary1 = {"a": ['1', '3'], "b": ['1', '2'], "c": ['2', '4']}  # dictionary
display(pd.DataFrame(dictionary1))

a  b  c
0  1  1  2
1  3  2  4

In [148]:
raw_data = {'col0': [1,2,3,4],
            'col1': [10,20,30,40],
            'col2': [100, 200, 300, 400]
}

In [149]:
data = pd.DataFrame(raw_data)
print(data)

   col0  col1  col2
0     1    10   100
1     2    20   200
2     3    30   300
3     4    40   400


In [150]:
data['col0']

0    1
1    2
2    3
3    4
Name: col0, dtype: int64

In [153]:
data.col0

0    1
1    2
2    3
3    4
Name: col0, dtype: int64

In [154]:
data.loc['col0']

KeyError: 'col0'

In [155]:
# 행을 골라야 함
data.loc[0]

col0      1
col1     10
col2    100
Name: 0, dtype: int64

데이터프레임은 해당 데이터의 컬럼명으로 출력해야함 or .loc[] or .iloc[] (특정 행에 접근해서 출력)
https://datascienceschool.net/01%20python/04.03%20%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84%20%EA%B3%A0%EA%B8%89%20%EC%9D%B8%EB%8D%B1%EC%8B%B1.html

In [151]:
data[0]

KeyError: 0

In [152]:
data[0,:]

InvalidIndexError: (0, slice(None, None, None))

In [156]:
# 딕셔너리 데이터는 순서가 없음
daeshin = {'open': [11650, 11100, 11200, 11100, 11100],
           'high': [12100, 11800, 11200, 11100, 11150],
           'low': [11600, 11050, 10900, 10950, 10900],
           'close': [11900, 11600, 11000, 11100, 11050]
}

daeshin_day = pd.DataFrame(daeshin)
print(daeshin_day)

    open   high    low  close
0  11650  12100  11600  11900
1  11100  11800  11050  11600
2  11200  11200  10900  11000
3  11100  11100  10950  11100
4  11100  11150  10900  11050


In [157]:
date = ['2016.02.29', '2016.02.26', '2016.02.25', '2016.02.24', '2016.02.23']
daeshin_day = pd.DataFrame(daeshin, columns = ['open', 'high', 'low', 'close'], index = date)

In [158]:
print(daeshin_day.columns)
print(daeshin_day.index)

Index(['open', 'high', 'low', 'close'], dtype='object')
Index(['2016.02.29', '2016.02.26', '2016.02.25', '2016.02.24', '2016.02.23'], dtype='object')


In [164]:
day_data = daeshin_day.loc['2016.02.24']
print(day_data)

open     11100
high     11100
low      10950
close    11100
Name: 2016.02.24, dtype: int64


In [166]:
print(type(day_data))

<class 'pandas.core.series.Series'>


In [165]:
daeshin_day.iloc[2]

open     11200
high     11200
low      10900
close    11000
Name: 2016.02.25, dtype: int64

In [167]:
series1 = pd.Series({"United Kingdom:":"London", "India:":"New Delhi", "United States":"Washington"})
display(series1)
display(pd.DataFrame(series1))

United Kingdom:        London
India:              New Delhi
United States      Washington
dtype: object

0
United Kingdom:      London
India:            New Delhi
United States    Washington

In [173]:
df = pd.DataFrame(series1)
df

0
United Kingdom:      London
India:            New Delhi
United States    Washington

In [174]:
df.columns()

TypeError: 'RangeIndex' object is not callable

In [175]:
df.columns

RangeIndex(start=0, stop=1, step=1)

In [176]:
df.columns = ['a', 'b', 'c']
df

ValueError: Length mismatch: Expected axis has 1 elements, new values have 3 elements

In [179]:
df.columns = ['capital']
df.columns

Index(['capital'], dtype='object')

In [180]:
print(df)

                    capital
United Kingdom:      London
India:            New Delhi
United States    Washington


In [182]:
df[["capital"]]

capital
United Kingdom:      London
India:            New Delhi
United States    Washington

In [184]:
df['United Kingdom'][0:2]  # 'B'라는 컬럼을 뽑은 후, 열에서 0부터 1까지의 출력


KeyError: 'United Kingdom'

In [185]:
df['capital'][0:2]  # 'B'라는 컬럼을 뽑은 후, 열에서 0부터 1까지의 출력

United Kingdom:       London
India:             New Delhi
Name: capital, dtype: object

In [187]:
df.iloc[0:2]

capital
United Kingdom:     London
India:           New Delhi

In [191]:
df.iloc[0:2]['London']  # index에서 0부터 1까지 지칭함

KeyError: 'London'

In [192]:
df.iloc[0]

capital    London
Name: United Kingdom:, dtype: object

In [193]:
df.iloc[0:2]

capital
United Kingdom:     London
India:           New Delhi

In [194]:
df.iloc["London"]

TypeError: Cannot index by location index with a non-integer key

In [ ]:
df.iloc[0:2]['capital']

United Kingdom:       London
India:             New Delhi
Name: capital, dtype: object

- 슬라이싱 기초

In [197]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [198]:
arr[5]

5

In [199]:
arr[5:8]

array([5, 6, 7])

In [200]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

- 뷰 대신에 슬라이스의 복사본을 얻고 싶은 경우, .copy() 사용

In [201]:
arr_slice_copy = arr[5:8].copy()
print(arr_slice_copy)

[12 12 12]


In [202]:
np.where(arr > 0, 2, -2)  # 양수는 모두 2, 음수는 모두 -1로

array([-2,  2,  2,  2,  2,  2,  2,  2,  2,  2])

In [203]:
arr.sum(0)  # default 행방향으로 axis=0, 열에 대한 합계

63

In [204]:
# 누적합계
arr.cumsum()

array([ 0,  1,  3,  6, 10, 22, 34, 46, 54, 63], dtype=int32)

In [205]:
arr.cumsum(0)  # 0 행방향 누적합

array([ 0,  1,  3,  6, 10, 22, 34, 46, 54, 63], dtype=int32)

In [210]:
arr1 = np.array([1,2], [3,4])

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [211]:
arr1 = np.array([[1,2], [3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [212]:
arr1.cumsum(1)  # 1 열방향 누적합

array([[1, 3],
       [3, 7]], dtype=int32)

- 불리언 배열을 위한 메소드

In [214]:
from numpy import *
arr2 = random.randn(100)  # 가우시안 표준정규분포에서 난수 매트릭스 배열 생성

(arr2 > 0).sum()  # 양수의 갯수

50

In [217]:
arr3 = random.randn(100, 2)
arr3

array([[-0.17889093,  0.93767403],
       [-0.2324053 , -0.91428516],
       [ 0.77091712,  0.40496448],
       [ 0.90207849, -0.58854405],
       [ 0.86938704, -0.78247277],
       [ 1.00699372,  0.96524408],
       [ 0.60612334,  0.66073098],
       [-1.05077617, -0.80944547],
       [ 0.47605849,  2.04061271],
       [ 0.44942114,  0.26116789],
       [ 0.58361633, -1.81274699],
       [-0.65201531,  0.95472305],
       [-0.39455692,  1.18009768],
       [-0.34321393,  0.86696466],
       [-0.16720031, -1.17886405],
       [ 1.19231726,  1.37016007],
       [-0.55312745,  0.05341672],
       [-1.99783186, -1.20635728],
       [-0.611651  , -1.26295875],
       [-0.68118897,  0.05515571],
       [ 0.58429064,  1.86015638],
       [-0.17713856, -0.13500706],
       [ 0.77204987,  0.97811196],
       [-0.8912007 , -0.54076476],
       [ 1.80889868, -1.49965837],
       [-0.3341116 ,  0.19508825],
       [-1.9245173 ,  1.60067192],
       [ 0.48045978,  0.45708496],
       [ 0.26030742,

In [218]:
arr3.sort(1)  # 열방향으로 sort

- 대소문자 다르게 취급함

In [220]:
# 중복제거
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'bob'])
print(names)

print(np.unique(names))

['Bob' 'Joe' 'Will' 'Bob' 'bob']
['Bob' 'Joe' 'Will' 'bob']


In [ ]:
np.in1d(values, [2,3,6])  # numpy.in1d(ar1, ar2, 가정_고유=False, 반전=False): 1차원 배열의 각 요소가 두번째 배열에도 있는지 테스트

#### NumPy Array에서 사용하는 concatenate() 함수 vs. Pandas DataFrame에서 사용하는 concat() 함수 

- hstack()
- vstack()
- concatenate()

- split()
- repeat() : 반복횟수와 기준 행/열 설정가능