### 1. 파이썬에서의 리스트 vs. 넘파이 다차원 배열

리스트 vs. 넘파이: 계산성능
넘파이는 대용량의 배열 & 행렬 연산 수행; ndarray 객체 제공

- 배열(array)은 동일한 자료형을 가진 데이터를 연속으로 저장

- 파이썬의 리스트 (여러 데이터의 나열)는 동일하지 않은 자료형을 가진 항목들을 담을 수 있음; 원소에 접근하는 속도가 매우 느림

- 넘파이의 ndarray 객체는 동일한 자료형의 항목들만 저장; 넘파이가 원소에 접근하는 속도가 더 빠름

#### 1) 리스트의 두 변수의 연산

In [1]:
store_a = [20, 10, 30]
store_b = [70, 90, 70]

In [2]:
list_sum = store_a + store_b

In [3]:
print(list_sum)

[20, 10, 30, 70, 90, 70]


#### 2) 넘파이의 다차원 배열

In [5]:
import numpy as np
np_store_a = np.array(store_a)
np_store_b = np.array(store_b)

np_store_sum = np_store_a + np_store_b
print(np_store_sum)

[ 90 100 100]


- 넘파이 배열의 인덱싱과 슬라이싱

In [8]:
np_store_sum.ndim  # 배열의 차원이 숫자로 나옴

1

- .astype()  # 열의 요소의 dtype을 변경
- .flatten()  # 넘파이 다차원 배열의 평탄화 메소드 (1차원화해줌)
- .T  # 전치행렬 수행; 속성값을 뱉어냄. method 아님; 2 * 3 행렬을 3 * 2 행렬로 바꿈
- .transpose()  # 전치행렬하는 메소드

In [11]:
import numpy as np
a = np.arange(1,7).reshape(2,3)
a
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

- 배열을 만든 후, 정렬

In [15]:
c = np.array([35, 24, 55, 69, 19, 99])
c.sort()  # 오름차순으로 정렬; 원행렬 자체를 정렬하고, 반환값은 none으로 나옴
print(c.sort())  # ndarray.sort() 방식
print(c)
c[::-1]  # 내림차순으로 정렬
print(c[::-1])

None
[19 24 35 55 69 99]
[99 69 55 35 24 19]


In [14]:
np.sort(c)

array([19, 24, 35, 55, 69, 99])

In [19]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort()  # 디폴트는 axis = 1 기준으로 정렬
d

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

다시

In [35]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort(axis = 0)  # axis = 0; 행방향으로 정렬, axis = 1; 열방향으로 정렬
d

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])

In [23]:
np.flip(d, axis = 1)  # 좌우 변환

array([[ 9,  1,  4],
       [11, 19, 35],
       [55, 24, 69]])

In [24]:
np.flip(d, axis = 0)  # 위아래 변환

array([[69, 24, 55],
       [35, 19, 11],
       [ 4,  1,  9]])

In [40]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])

In [41]:
d.sort()
d
np.flip(d, axis = 0)

array([[ 1,  4, 11],
       [ 9, 19, 69],
       [24, 35, 55]])

In [42]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])

In [43]:
d_flipped = np.flip(d, axis = 1)
d_flipped

array([[55, 24, 35],
       [ 9, 19, 69],
       [11,  1,  4]])

In [31]:
d_flipped = np.flip(d, axis = 1)
d_flipped

array([[ 1,  4,  9],
       [11, 19, 35],
       [24, 55, 69]])

In [37]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])

In [38]:
d.sort()
d
np.flip(d, axis = 1)

array([[55, 35, 24],
       [69, 19,  9],
       [11,  4,  1]])

In [45]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort(axis=0)  # 행방향으로 sort
d

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])

##### 참고: https://rfriend.tistory.com/357

In [ ]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort(axis=0)  # 행방향으로 descending하는 방식으로 sort
# 이를 행방향으로 flip

In [57]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d1 = np.sort(d)[::-1]  # 또는 x[np.argsort(-x)]  # 행방향으로 descending하는 방식으로 sort
d1# 이를 행방향으로 flip

array([[ 1,  4, 11],
       [ 9, 19, 69],
       [24, 35, 55]])

In [55]:
np.flip(d1, axis = 0)

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

In [58]:
np.flip(d1, axis = 1)

array([[11,  4,  1],
       [69, 19,  9],
       [55, 35, 24]])

-----

In [59]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d1 = np.sort(d, axis = 0)[::-1]  # 또는 x[np.argsort(-x)]  # 행방향으로 descending하는 방식으로 sort
np.flip(d1, axis = 0)# 이를 행방향으로 flip

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])

- 다차원 배열을 위한 .append() 함수와 행렬의 곱셈

In [47]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.append([a], b, axis = 0)  # [a]를 통해 2차원 배열로 만들어야 함

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a = np.array([[1,2], [3,4]])  # 2차원 배열 a
b = np.array([[10,20], [30,40]])  # 2차원 배열 b
a * b

array([[ 10,  40],
       [ 90, 160]])

- 행렬의 연산곱셈을 할 때는, matmul() 함수 사용; @ 연산자 사용

In [51]:
np.matmul(a, b)

array([[ 70, 100],
       [150, 220]])

In [50]:
a @ b

array([[ 70, 100],
       [150, 220]])

- 배열의 형태를 바꾸는 .reshape()  
튜플값으로 제공하나, reshape((x, y)) 로 해줘야하지만, 튜플은 자유로운 형태를 가지므로 원소의 갯수/행렬의 특성만 맞으면 .reshape()로 변환

> .reshape(a, -1)  # -1 사용 중요

In [ ]:
y.reshape(6, -1)  # 주어진 데이터에서 행은 무조건 6개로, 열은 마음대로 처리하라는 뜻. 데이터 형태가 호환되는 선에서

In [53]:
a.reshape(1, -1)

array([[1, 2, 3, 4]])

> .reverse()

In [61]:
a.reverse()

AttributeError: 'numpy.ndarray' object has no attribute 'reverse'

In [62]:
a[::-1]

array([[3, 4],
       [1, 2]])

#### 3) 난수

In [65]:
np.random.randint(150, 191, size = 10)  # 시작점 (이상)과 끝지점 (미만), 총 몇개의 데이터를 만들 것인지 지정해주어야 함

array([165, 170, 150, 151, 158, 172, 153, 190, 175, 173])

- 표준정규분포

In [68]:
rnd = np.random.randn(5)  # 평균이 0이고, 분산이 1인 표준정규분포
rnd

array([ 0.68129257,  0.15847644, -1.15131334, -0.13103949,  0.54394415])

In [72]:
rnd = np.random.randn(5) * 10 + 165  # 평균이 165, 표준편차가 10인 값
rnd

array([169.96714153, 163.61735699, 171.47688538, 180.23029856,
       162.65846625])

In [73]:
rnd.round(2)  # 소수점 아래 둘째자리까지 값으로 변환

array([169.97, 163.62, 171.48, 180.23, 162.66])

In [74]:
rnd.astype(int)  # 정수형 자료형으로 변환
np.random.seed(42)

In [75]:
print(np.random.seed(42))

None


In [76]:
print(np)

<module 'numpy' from 'C:\\Users\\Conet\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


- 평균 165, 표준편차 10인 표준정규분포 만들기

In [77]:
nums = np.random.normal(loc = 165, scale = 10, size = (3, 4)).round(2)
nums

array([[169.97, 163.62, 171.48, 180.23],
       [162.66, 162.66, 180.79, 172.67],
       [160.31, 170.43, 160.37, 160.34]])

- rand()
- randn()
- randint()
- normal()
- uniform()
- shuffle(); 순서만 뒤섞음
- permutation(); 순서가 뒤섞인 채로 array로 뱉어냄

In [79]:
a = np.arange(10)
a
print(a)
np.random.shuffle(a)
a

[0 1 2 3 4 5 6 7 8 9]


array([1, 5, 4, 8, 0, 7, 6, 3, 2, 9])

- numpy 스타일의 슬라이싱과 논리 인덱싱

In [80]:
arr_2d = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [0,1,2]])
arr_2d[1:, 0:2]

array([[4, 5],
       [7, 8],
       [0, 1]])

- np_array[::2, ::2]와 np_array[::2] (행에 대해서만 슬라이싱)의 차이 알기

In [84]:
np_array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
np_array % 2 == 0  # 짝수일때만 True, 홀수일때는 False 반환

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [85]:
np_array[np_array % 2 == 0]  # 논리값으로 배열된, 즉 True에 해당하는 값만 출력돼서 나옴

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 4) 리덕션: 배열을 더 강력하게 만드는 기능

넘파이의 다차원 배열은 reduction이라는 여러개의 수로 이루어진 배열을 하나의 수로 집계하는 것; sum(), mean(), min(), max()와 같은 함수 제공

행의 합과 열의 합을 구하는 것

다시

In [87]:
arr = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
np.sum(arr, axis = (0, 1))  # 이 것이 의미하는 바는?

[ 4  8 12 16 20]
[15 15 15 15]


60

In [89]:
import numpy as np
import time

n = 1000
arr = np.random.rand(n, n)

In [91]:
print(n)
print(arr)

1000
[[0.68030754 0.45049925 0.01326496 ... 0.45514369 0.52243458 0.64454665]
 [0.65016735 0.36469725 0.56067719 ... 0.97955084 0.14496507 0.72515573]
 [0.1911907  0.33826311 0.30869874 ... 0.78486182 0.73348675 0.11619096]
 ...
 [0.84191823 0.73115233 0.62236669 ... 0.593282   0.16515692 0.12972237]
 [0.55262818 0.2832132  0.75042099 ... 0.53923084 0.18329225 0.31264177]
 [0.41317965 0.51189017 0.98597978 ... 0.35034709 0.20133581 0.86650407]]


In [93]:
sum_naive = 0
start = time.time()
for i in range(n):
    for j in range(n):
        sum_naive += arr[i,j]
end = time.time()
print(n, 'x', n, '배열의 원소 합', sum_naive, '\n계산 시간', end-start)

1000 x 1000 배열의 원소 합 500053.4795674659 
계산 시간 0.2919142246246338


In [96]:
start = time.time()
sum_reduction = np.sum(arr, axis = (0,1))
end = time.time()
print(n, "x", n, "배열의 원소 합", sum_reduction, "\n계산 시간: ", end-start)

1000 x 1000 배열의 원소 합 500053.47956746415 
계산 시간:  0.0019943714141845703


In [97]:
a = np.arange(10, 18).reshape(2,4)
b = np.arange(12).reshape(3,4)
c = np.arange(8).reshape(2,4)
d = list(range(4))
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [98]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [100]:
d

[0, 1, 2, 3]

- 배열의 결합 (concatenate, vstack, hstack)

In [102]:
np.concatenate((a,b))  # a배열의 마지막 원소 뒤에 b배열의 원소를 차례로 넣음

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
np.vstack((a,b))  # a배열과 b배열을 수직 방향으로 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 다차원 배열과 브로드캐스팅

In [104]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [105]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [107]:
np.full((2,3), 100)

array([[100, 100, 100],
       [100, 100, 100]])

In [109]:
np.eye(3)  # 단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [110]:
a1 = np.eye(6)

In [111]:
a1

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [112]:
lis1 = []
for i in a1[i]:
    i = 0
    i += i
    list1.append(i)
    print(list1)

IndexError: index 999 is out of bounds for axis 0 with size 6

문제 1

In [115]:
n = list(range(1,7,1))
a1 * n

array([[1., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 6.]])

- np.diag() : k를 지정해서 k차원 대각행렬 구할 수 있음

In [116]:
n = int(input('n을 입력하시오: '))
a = np.diag(1+np.arange(n), k = 0)
print(a)

n을 입력하시오:  6


[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [122]:
np.diag(np.arange(5), k = 0)

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [121]:
n = int(input('n을 입력하시오: '))
a = np.diag(1+np.arange(n), k = 2)
print(a)

n을 입력하시오:  5


[[0 0 1 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 0 3 0 0]
 [0 0 0 0 0 4 0]
 [0 0 0 0 0 0 5]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [118]:
n = int(input('n을 입력하시오: '))
a = np.eye(n)
for i in range(1, n+1):
    for j in range(1, n+1):
        if i == j:
            a[i][j] = i

a

n을 입력하시오:  6


IndexError: index 6 is out of bounds for axis 0 with size 6

In [120]:
n = int(input('n을 입력하시오: '))
a = np.eye(n)
for i in range(1, n+1):
    for j in range(1, n+1):
        if i == j:
            a[i][j] = i
            print(a)

a

n을 입력하시오:  6


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0. 5.]]


IndexError: index 6 is out of bounds for axis 0 with size 6

In [119]:
n = int(input('n을 입력하시오: '))
a = np.eye(n)
for i in range(0,n):
    for j in range(0,n):
        if i == j:
            a[i][j] = i

a

n을 입력하시오:  6


array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 0., 5.]])

문제 2

In [173]:
n = int(input('n을 입력하시오: '))

a = np.ones((n, n))
a

n을 입력하시오:  5


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [126]:
b = np.zeros((n, n))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

-----

In [131]:
n = int(input('n을 입력하시오: '))

a = np.ones((n, n), dtype = 'int32')  # dtype을 지정해주지 않으면, 실수값으로 나오므로 정수값으로 변환해주어야 함
print('a 행렬')
print(a)
b = a
b[1:-1, 1:-1] = 0  # 끝 바로 앞까지; 즉 -2까지 0으로 만들어준다는 뜻
print('b 행렬')
print(b)

n을 입력하시오:  5


a 행렬
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
b 행렬
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


문제 3

In [132]:
n = int(input('n을 입력하시오: '))

a = np.zeros((n, n), dtype = 'int32')  # dtype을 지정해주지 않으면, 실수값으로 나오므로 정수값으로 변환해주어야 함
print('a 행렬')
print(a)
b = a
b[1:-1, 1:-1] = 1  # 끝 바로 앞까지; 즉 -2까지 0으로 만들어준다는 뜻
print('b 행렬')
print(b)

n을 입력하시오:  5


a 행렬
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
b 행렬
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [133]:
n = int(input('n을 입력하시오: '))
a = np.ones((n,n), dtype = 'int32')
print(a)
c = a
c[0, :] = c[-1, :] = c[:, 0] = c[:, -1] = 0
print('c행렬')
print(c)

n을 입력하시오:  5


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c행렬
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [136]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
a

array([1, 2, 3])

In [137]:
np.r_[a, b]  # a, b 배열을 결합함; np.hstack([a, b])

array([ 1,  2,  3, 10, 20, 30])

In [138]:
np.r_[a, 4, 5, 6, b]  # 중간에 개별 원소 삽입도 가능

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30])

In [142]:
np.r_[[0] * 3, 5, 6]

array([0, 0, 0, 5, 6])

In [140]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[10, 20, 30], [40, 50, 60]])

In [141]:
np.r_[c, d]  # 2차원 배열을 axis = 0 방향으로 결합

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [145]:
np.r_[a.reshape(-1,1), b.reshape(-1,1)]  # a, b를 2차원 배열로 만들어서 axis = 0 방향으로 결합; 행은 모르겠고, 열이 1개인 배열을 만들어서 뱉어줌

array([[ 1],
       [ 2],
       [ 3],
       [10],
       [20],
       [30]])

In [146]:
np.concatenate((a.reshape(-1, 1), b.reshape(-1, 1)), axis = 1)

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [147]:
np.c_[a, b]

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [148]:
np.column_stack([a, b])

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [150]:
np.concatenate((c.T, d.T), axis = 1)  # c와 d의 전치행렬 결합

array([[ 1,  4, 10, 40],
       [ 2,  5, 20, 50],
       [ 3,  6, 30, 60]])

In [152]:
list1 = [1, 2, 'test']
array2 = np.array(list1)
print(array2, array2.dtype)

list2 = [1, 2, 3.0]
array3 = np.array(list2)  # 정수형 값들이 데이터 사이즈가 큰 float 형태로 바뀜
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [ ]:
array_int = 

In [153]:
array2 = np.array([[1,2,3], [4,5,6]])

print(array2.sum())
print(array2.sum(axis = 0))
print(array2.sum(axis = 1))

21
[5 7 9]
[ 6 15]


In [155]:
array2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [156]:
array2.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [157]:
array2.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [158]:
array12 = np.arange(10)

In [159]:
array12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
array12.reshape(-1, 1)  # 2차원으로 변환

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [161]:
array12.reshape(-1,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- 반드시 -1값은 1개으이 인자만 입력해야 함 (그렇지 않으면 오류 발생)

In [163]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)  # 3차원
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [164]:
# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape())

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]


TypeError: 'tuple' object is not callable

In [165]:
# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [167]:
array1d = np.arange(start = 1, stop = 10)

다시

In [168]:
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
array3

array([3, 6])

In [169]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
array3 = array1d[array1d > 5]  # boolean index
array3

array([6, 7, 8, 9])

#### 5) np.sort()와 ndarray.sort() 정렬의 차이
- np.sort(); 원행렬은 그대로 유지한 채, 원행렬의 정렬된 행렬 반환
- ndarray.sort(); 원행렬 자체를 정렬한 형태로 반환하고, 반환값은 None

모두 기본적으로 오름차순으로 정렬함

np.darray[::-1]

In [175]:
org_array = np.array([3, 1, 9, 5])
print(np.sort(org_array))

sort_indices = np.argsort(org_array)  # 행렬 정렬 시 원본 행렬의 인덱스
print(sort_indices)
print(type(sort_indices))

[1 3 5 9]
[1 0 3 2]
<class 'numpy.ndarray'>


In [176]:
org_array[1,3] = 12
org_array

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [177]:
org_array[1:3] = 12
org_array

array([ 3, 12, 12,  5])

- 리스트 내에 리스트 형태의 데이터가 존재하는 목록형 데이터의 경우,

    원본에 영향을 미치지 않아야 하는 경우에는 deepcopy() 사용

배열복사에서는 행과 열을 기준으로 원본이 변하는지, 사본지 변화하는지 알아보고 이용

In [179]:
np.full(2,3), 3

(array([3, 3]), 3)

- .dot() 메소드

- 2 * a  # array 연산
- a _ b  # array 더하기 연산

문제 1

In [198]:
a = np.array([0, 10, 20, 40, 60, 80])
print('a 배열:', a)
b = np.arange(0,30,20)
print('b 배열:', b)

t = np.full(a.shape, False)
ind = 0
for x in a:
    if x in b:
        t[ind] = True
    ind += 1
    
print(t)

a 배열: [ 0 10 20 40 60 80]
b 배열: [ 0 20]
[ True False  True False False False]


문제 1

In [195]:
x = np.array([[10,20,40,60], [10, 20, 40, 40]])

In [196]:
x

array([[10, 20, 40, 60],
       [10, 20, 40, 40]])

In [197]:
np.full(x.shape, False)

array([[False, False, False, False],
       [False, False, False, False]])

In [204]:
np.full(x.shape, False)

array(False)

In [207]:
print(x)
x.flatten()

80


array([80])

In [208]:
unique, counts = np.unique(x, return_counts=True)

print(unique)
print(counts)

[80]
[1]


In [209]:
for x, y in np.array((unique, counts)).T:
    print('{:3d} :{:2d}번'.format(x, y))

 80 : 1번


In [210]:
x = np.array([[10,20,40,60], [10, 20, 40, 40]])
print(x)
x.flatten()

unique, counts = np.unique(x, return_counts=True)

print(unique)
print(counts)

for x, y in np.array((unique, counts)).T:
    print('{:3d} :{:2d}번'.format(x, y))

[[10 20 40 60]
 [10 20 40 40]]
[10 20 40 60]
[2 2 3 1]
 10 : 2번
 20 : 2번
 40 : 3번
 60 : 1번


문제 2

In [214]:
x = np.arange(15,24)
x

array([15, 16, 17, 18, 19, 20, 21, 22, 23])

In [215]:
x.reshape(3,3)

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [211]:
x = np.array([[15, 16, 17], [18, 19, 20], [21, 22, 23]])

In [212]:
x

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

문제 3

In [217]:
x1 = np.arange(1,5)
x2 = np.arange(5,9)
print(x1)
print(x2)

[1 2 3 4]
[5 6 7 8]


In [219]:
x1 == x2

array([False, False, False, False])

In [227]:
x1 = np.arange(1,5)
x2 = np.arange(5,9)

result = np.full(x1.size, False)
for i in range(x1.size):
    print(x1[i], x2[i])
    if x1[i] == x2[i]:
        result[i] = True
result

1 5
2 6
3 7
4 8


array([False, False, False, False])

문제 4

In [220]:
중간고사 = 15, 100, 45
기말고사 = 78, 25, 90
과제 = 81, 45, 99

In [231]:
x1 = np.array([[15, 100, 45], [78, 25, 90], [81, 45, 99]])
x1

array([[ 15, 100,  45],
       [ 78,  25,  90],
       [ 81,  45,  99]])

In [236]:
x1_w = x1 * [0.4, 0.4, 0.2]
x1_w

array([[ 6. , 40. ,  9. ],
       [31.2, 10. , 18. ],
       [32.4, 18. , 19.8]])

In [237]:
x1 + x1_w

array([[ 21. , 140. ,  54. ],
       [109.2,  35. , 108. ],
       [113.4,  63. , 118.8]])

In [239]:
x1_we = x1 + x1_w

In [240]:
x1_we

array([[ 21. , 140. ,  54. ],
       [109.2,  35. , 108. ],
       [113.4,  63. , 118.8]])

In [249]:
_s = np.ones((3,3)) * 5
_s

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [251]:
m_f = x1_we + _s
m_f

array([[ 26. , 145. ,  59. ],
       [114.2,  40. , 113. ],
       [118.4,  68. , 123.8]])

In [256]:
print(m_f.mean())
print(m_f.std())

89.7111111111111
39.62166759753906


In [257]:
m_f[2:]

array([[118.4,  68. , 123.8]])

------

In [258]:
import numpy as np
mid = np.array([15, 100, 45])
fin = np.array([78, 25, 90])
hw = np.array([81, 45, 99])

total = 0.4*mid+0.4*fin+0.2*hw+5

print(total)

print(mid.mean())
print(mid.std())
print(total[0])

[58.4 64.  78.8]
53.333333333333336
35.19785346990479
58.400000000000006
