문제 1

In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
b = a[1:3]
b[0] = 4
print(a)

[1 4 3 4 5]


----

문제 2

In [36]:
a = np.array([1, 4, 3, 7, 9, 10]).reshape(2,3)
print(a)

[[ 1  4  3]
 [ 7  9 10]]


In [5]:
a1 = a.copy()
print(a1)
def ones_like:
    for i in a1:
        for j in 
    

[[ 1  4  3]
 [ 7  9 10]]


-----

In [37]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

문제 3

In [38]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a[1, :], type(a[1, :]))  # 1차원
print(a[1:2, :], type(a[1:2, :]))  # 2차원

[4 5 6] <class 'numpy.ndarray'>
[[4 5 6]] <class 'numpy.ndarray'>


문제 4

반복문 사용해서 append 하는 방법? 

In [8]:
a = np.array([2,4,6,8,10])
print(a)

[ 2  4  6  8 10]


In [11]:
a[:4] = 2
a[4:6] = 4
np.append(a, [4, 6, 6])

array([2, 2, 2, 2, 4, 4, 6, 6])

---

In [39]:
a = np.array([2,4,6,8,10])
idx=np.array([0,0,0,0,1,1,2,2])
c=a[idx]
c

array([2, 2, 2, 2, 4, 4, 6, 6])

문제 5

In [15]:
a2 = np.random.randn(4,4)
print(a2)

np.where(a2 > 0, 1, -1)

[[ 0.05375159 -1.45344101 -0.62508936  1.1506556 ]
 [ 0.70100322  1.09833919  0.5918419  -0.04461896]
 [ 1.86784958  0.61104864 -0.27244007 -0.73880778]
 [ 0.87253187 -1.06612961  0.21646624 -1.03302584]]


array([[ 1, -1, -1,  1],
       [ 1,  1,  1, -1],
       [ 1,  1, -1, -1],
       [ 1, -1,  1, -1]])

---

In [40]:
import random
arr = np.random.randn(4,4)
arr
np.where(arr > 0, 1, -1)

array([[-1, -1,  1,  1],
       [-1,  1,  1,  1],
       [ 1, -1, -1, -1],
       [ 1, -1,  1,  1]])

문제 6

In [20]:

arr = np.random.randn(100)
print(arr)

for i in np.random.randn(100):
    if i > 0:
        print(np.unique(arr, return_counts = True))

[ 5.67566370e-01 -2.68750367e-01  2.01698024e+00 -6.11041510e-01
 -5.04686114e-01 -1.73334339e-01  2.49367373e-01  2.27393688e-01
 -1.27736769e-01 -8.97248948e-01  9.09348331e-01  6.14526986e-02
  6.48965940e-01  6.60189328e-01  6.16699179e-01  1.72230212e-02
  8.37864125e-01 -2.86213434e-01  8.78888136e-01 -4.40614328e-02
 -8.50888924e-01 -1.23871339e-01 -1.83495944e-03  1.70235118e-01
 -7.24337395e-01 -1.79443826e+00 -1.84086718e+00 -9.05372424e-01
  1.53121384e+00  1.70829994e+00  5.44063621e-01  3.89351409e-01
 -1.56450824e-01  1.02115430e+00  4.69774459e-01 -3.18183815e-01
  2.98604051e-01  3.94186757e-01 -1.06233582e+00  2.47507060e-01
 -3.34381809e-01 -2.38792395e+00 -9.80836623e-01  1.37591752e+00
 -6.04006309e-02  6.13668494e-01  1.35020334e+00 -2.20594471e+00
 -1.01032018e-02 -2.84767810e-01  1.21095191e-01 -4.38192839e-01
  8.94055067e-01 -4.32106751e-01  1.47399264e-01  5.53018712e-01
 -5.41767223e-02 -9.40368082e-01 -5.92125867e-01 -2.44404160e-01
  7.17740364e-01  1.40256

---

In [41]:
from numpy import *
arr = random.randn(100)
arr

(arr>0).sum()  # 양수의 갯수

48

문제 7

In [21]:
import pandas as pd
sdata = {'Ohio': 35000,
        'Texas': 71000,
        'Oregon': 16000,
        'Utah': 5000}

print(sdata)
sdata_series = pd.Series(sdata)
print(sdata_series)

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64


In [22]:
sdata_series['Texas']

71000

In [24]:
sdata_series[1]

71000

---

In [42]:
a = {'Ohio': 35000,
        'Texas': 71000,
        'Oregon': 16000,
        'Utah': 5000}
a = pd.Series(a)
a['Texas']

71000

문제 8

In [25]:
a2 = np.array([[1,2,3], [4,5,6]])
a3 = np.array([[7,8,9], [10,11,12]])
print(a2)
print(a3)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [27]:
np.concatenate([a2,a3], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
np.vstack([a2,a3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

---

In [43]:
np.concatenate((a2,a3), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
np.vstack((a2,a3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

문제 9

In [29]:
a4 = np.random.randn(5,5)
print(a4)

[[-1.11439671  0.10204851  0.48908315 -0.80518467  1.00773747]
 [-0.17669079 -0.62588627 -2.09294781  1.2938987  -0.44173587]
 [-0.50454561 -0.6986992   1.06532715  0.54463814  0.75655156]
 [ 0.18085748 -0.82267458  0.71346099  1.06553998  0.67289089]
 [ 1.28094576 -0.658059    0.04172528  0.71917173  0.65171659]]


In [30]:
a5 = a4.T
a5

array([[-1.11439671, -0.17669079, -0.50454561,  0.18085748,  1.28094576],
       [ 0.10204851, -0.62588627, -0.6986992 , -0.82267458, -0.658059  ],
       [ 0.48908315, -2.09294781,  1.06532715,  0.71346099,  0.04172528],
       [-0.80518467,  1.2938987 ,  0.54463814,  1.06553998,  0.71917173],
       [ 1.00773747, -0.44173587,  0.75655156,  0.67289089,  0.65171659]])

In [31]:
np.dot(a4,a5)

array([[ 3.15535342, -2.37757382,  1.33586739, -0.11641704, -1.39653537],
       [-2.37757382,  6.67268823, -1.3327087 ,  0.07116901,  0.74085873],
       [ 1.33586739, -1.3327087 ,  2.74666975,  2.33303095,  0.74268636],
       [-0.11641704,  0.07116901,  2.33303095,  2.80668707,  2.00764678],
       [-1.39653537,  0.74085873,  0.74268636,  2.00764678,  3.01754719]])

---

In [46]:
np.matmul(a4,a5)

array([[ 3.15535342, -2.37757382,  1.33586739, -0.11641704, -1.39653537],
       [-2.37757382,  6.67268823, -1.3327087 ,  0.07116901,  0.74085873],
       [ 1.33586739, -1.3327087 ,  2.74666975,  2.33303095,  0.74268636],
       [-0.11641704,  0.07116901,  2.33303095,  2.80668707,  2.00764678],
       [-1.39653537,  0.74085873,  0.74268636,  2.00764678,  3.01754719]])

문제 10

In [34]:
a6 = np.random.randn(4,4)
print(a6)
a6_df = pd.DataFrame(a6)
print(a6_df)
print(display(a6_df[:]))

[[ 0.19728103 -1.52365251  1.17302102 -0.02880542]
 [-0.94537894 -0.01634099 -0.12759672  0.47938721]
 [-0.47115056 -1.83196171  1.26292599 -0.95739819]
 [-1.06333895 -0.18118365 -1.24341678  0.36837319]]
          0         1         2         3
0  0.197281 -1.523653  1.173021 -0.028805
1 -0.945379 -0.016341 -0.127597  0.479387
2 -0.471151 -1.831962  1.262926 -0.957398
3 -1.063339 -0.181184 -1.243417  0.368373


0         1         2         3
0  0.197281 -1.523653  1.173021 -0.028805
1 -0.945379 -0.016341 -0.127597  0.479387
2 -0.471151 -1.831962  1.262926 -0.957398
3 -1.063339 -0.181184 -1.243417  0.368373

None


---

In [45]:
display(a6_df.iloc[1:3])

0         1         2         3
1 -0.945379 -0.016341 -0.127597  0.479387
2 -0.471151 -1.831962  1.262926 -0.957398