문제 1

In [11]:
import numpy as np
a = np.array([0, 10, 20, 40, 60, 80])
b = np.array([0, 20])

c = np.append([a], b)
c

array([ 0, 10, 20, 40, 60, 80,  0, 20])

-----

In [45]:
import numpy as np
a = np.array([0, 10, 20, 40, 60, 80])
b = np.array([0, 20])

c = np.array([])

for n in a:
    if n not in b:
        c = np.append(c, n)
print(c)

[10. 40. 60. 80.]


In [51]:
print('a - b:', np.setdiff1d(a,b))

a - b: [ 1  2  3  4  5  6  7  8  9 10]


문제 2

In [13]:
a = np.arange(1,11,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
a.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

----

In [49]:
a=np.arange(1,11).reshape(-1,1)
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


문제 3

In [16]:
a.reshape(10,1)[::-1]

array([[10],
       [ 9],
       [ 8],
       [ 7],
       [ 6],
       [ 5],
       [ 4],
       [ 3],
       [ 2],
       [ 1]])

---

In [52]:
np.sort(a)[::-1]

array([[10],
       [ 9],
       [ 8],
       [ 7],
       [ 6],
       [ 5],
       [ 4],
       [ 3],
       [ 2],
       [ 1]])

문제 4

In [17]:
x1 = np.arange(10,26,1)
x1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [18]:
x1.reshape(4,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

----

In [54]:
a=np.arange(10, 26).reshape(4,4)
print(a)
a.sum(axis=0)
print(a.sum(axis=0))
a.sum(axis=1)
print(a.sum(axis=1))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[64 68 72 76]
[46 62 78 94]


문제 5

In [19]:
x = np.array([10, 20, 40, 60, 10, 20, 40, 40, 40])
x

array([10, 20, 40, 60, 10, 20, 40, 40, 40])

다시

In [20]:
x = np.array([10, 20, 40, 60, 10, 20, 40, 40, 40])
print(x)
x.flatten()

unique, counts = np.unique(x, return_counts=True)

print(unique)
print(counts)

for x, y in np.array((unique, counts)).T:
    print('{:3d} :{:2d}번'.format(x, y))

[10 20 40 60 10 20 40 40 40]
[10 20 40 60]
[2 2 4 1]
 10 : 2번
 20 : 2번
 40 : 4번
 60 : 1번


---

In [55]:
x = np.array([10, 20, 40, 60, 10, 20, 40, 40, 40])
print(x)
# x.flatten()

unique, counts = np.unique(x, return_counts=True)

print(unique)
print(counts)

for x, y in np.array((unique, counts)).T:
    print('{:3d} :{:2d}번'.format(x, y))

[10 20 40 60 10 20 40 40 40]
[10 20 40 60]
[2 2 4 1]
 10 : 2번
 20 : 2번
 40 : 4번
 60 : 1번


문제 6

In [22]:
array1 = np.arange(5)

In [23]:
array1

array([0, 1, 2, 3, 4])

In [24]:
array1.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

----

In [56]:
array1 = np.arange(5)

array2 = array1.reshape(-1,1)  # 1차원 배열을 2차원 배열로 변경해줌
print(array2)

[[0]
 [1]
 [2]
 [3]
 [4]]


문제 7

In [25]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
array3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
array3d.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

---

In [57]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))

array2d = array3d.reshape(-1,1)
print(array2d)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


문제 8

In [32]:
n = int(input('n을 입력하시오: '))

n1 = np.eye(n, dtype = 'int32')
n1

n을 입력하시오:  5


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
n1 = np.diag(np.arange(n), k = 0)
n1

----

In [58]:
n = int(input('n을 입력하시오: '))

a = np.full((n, n), 0)
# a = np.zeros(n)

for i in range(n):
    for j in range(n):
        if i >= j:
            a[i, j] = 1

print(a)

n을 입력하시오:  5


[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


문제 9

In [61]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
array2d[array2d > 7]

array([8, 9])

----

In [63]:
array2d[2,:-1]

array([7, 8])

In [62]:
array2d[2,1:]

array([8, 9])

문제 10 내림차순으로 정렬하기

In [42]:
name = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score = np.array([22, 44, 84, 10, 88])

score[::-1]

array([88, 10, 84, 44, 22])

In [38]:
name = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score = np.array([22, 44, 84, 10, 88])

name_score = np.append(name, score)
name_score

array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel', '22', '44', '84', '10',
       '88'], dtype='<U11')

In [39]:
name_score[::-1]

array(['88', '10', '84', '44', '22', 'Samuel', 'Kate', 'Sarah', 'Mike',
       'John'], dtype='<U11')

----

In [64]:
sort_indices = np.argsort(score)[::-1]
print('성적 오름차순 정렬 시 score의 인덱스:', sort_indices)

name_array_sort = name[sort_indices]
score_array_sort = score[sort_indices]

print('성적 오름차순으로 name_array의 이름 출력:', name_array_sort)
print('성적 오름차순으로 score_array의 점수 출력:', score_array_sort)

성적 오름차순 정렬 시 score의 인덱스: [4 2 1 0 3]
성적 오름차순으로 name_array의 이름 출력: ['Samuel' 'Sarah' 'Mike' 'John' 'Kate']
성적 오름차순으로 score_array의 점수 출력: [88 84 44 22 10]
