문제 1

In [45]:
x, y = input('점의 좌표 x, y를 입력하시오 : ').split()
x = int(x)
y = int(y)
if x > 0 and y > 0:
 print('1사분면에 있음')
elif x > 0 and y < 0:
 print('4사분면에 있음')
elif x < 0 and y > 0:
 print('2사분면에 있음')
else:
 print('3사분면에 있음')

점의 좌표 x, y를 입력하시오 :  2 4


1사분면에 있음


문제 2

In [8]:
import pandas as pd
import numpy as np

a = int(input('세 수를 입력하시오'))
b = int(input('세 수를 입력하시오'))
c = int(input('세 수를 입력하시오'))

list_abc = [a, b, c]

print(sum(list_abc) / len(list_abc))
print(max(a, b, c))
print(min(a, b, c))

세 수를 입력하시오 10
세 수를 입력하시오 30
세 수를 입력하시오 20


20.0
30
10


In [57]:
def mean3(a, b, c):
    return (a+b+c)/3

def max3(a, b, c):
    max = a
    if b > c:
        if max > b:
            return max
        else :
            return b
        else :
            if max > c:
                return max
            else:
                return c

def min3(a, b, c):
    m1 = a
    if b > c:
        m2 = c
        else:
            m2 = b
            if m1 > m2:
                return m2
            else:
                return m1
a, b, c = input('세 수를 입력하시오 :').split()
a, b, c = int(a), int(b), int(c)
print(a, ",", b, ",", c, "의 평균값은", mean3(a, b, c))
print(a, ",", b, ",", c, "의 최댓값은", max3(a, b, c))
print(a, ",", b, ",", c, "의 최솟값은", min3(a, b, c))

SyntaxError: invalid syntax (1189655955.py, line 11)

문제 3

In [9]:
l1 = ['I like', 'I love']
l2 = ['fan cake.', 'kiwi juice.', 'espresso.']

In [13]:
l1[0] + ' '+ l2[0]

'I like fan cake.'

In [15]:
l1[0] + ' '+ l2[1]

'I like kiwi juice.'

In [17]:
l1[0] + ' '+ l2[2]

'I like espresso.'

In [49]:
l1 = ['I like', 'I love']
l2 = ['fan cake.', 'kiwi juice.', 'espresso.']

for i in l1:
    for j in l2:
        print(i,j)

I like fan cake.
I like kiwi juice.
I like espresso.
I love fan cake.
I love kiwi juice.
I love espresso.


문제 4

In [18]:
scores = ( ('박동규', 88, 95, 90), ('강영민', 85, 90, 95), ('박동민', 70, 90, 80), ('홍승주', 90, 90, 95))
scores

(('박동규', 88, 95, 90),
 ('강영민', 85, 90, 95),
 ('박동민', 70, 90, 80),
 ('홍승주', 90, 90, 95))

In [20]:
list(scores)

[('박동규', 88, 95, 90),
 ('강영민', 85, 90, 95),
 ('박동민', 70, 90, 80),
 ('홍승주', 90, 90, 95)]

In [26]:
(list(scores)[0][2] + list(scores)[1][2] + list(scores)[2][2] + list(scores)[3][2]) / 4

91.25

In [52]:
_, _, math, science = zip(*scores)

In [53]:
total = 0
for n in math:
    total += n
print('학생들의 수학 성적의 평균은 {0:5.2f}입니다.'.format(total/len(math)))

학생들의 수학 성적의 평균은 91.25입니다.


문제 5

In [ ]:
x = int(input("1~20까지의 숫자를 입력하세요: "))
for i in x:
    if

In [59]:
import random # 난수를 만드는 random 모듈 사용
x = random.randint(1, 20) # 1~20 난수 발생
number=-1
n = 0
# while 무한 루프
while number!= x :
    number = int(input("1~20까지의 숫자를 입력하세요: "))
    n += 1
    if x == number : # 정답이면 break
        print("정답입니다!")
    elif x > number :
        print(number, "보다 큽니다!")
    else :
        print(number, "보다 작습니다!")
    
# 평가 출력
if n <= 3 :
    print(n, "번만에 맞춘 당신은 천재!")
elif n <= 6 :
    print(n, "번만에 맞추셨네요. 잘했어요^^")
else :
    print(n, "번만에 맞추다니 쩝쩝...")

1~20까지의 숫자를 입력하세요:  15


15 보다 작습니다!


1~20까지의 숫자를 입력하세요:  14


14 보다 작습니다!


1~20까지의 숫자를 입력하세요:  13


13 보다 작습니다!


1~20까지의 숫자를 입력하세요:  12


12 보다 작습니다!


1~20까지의 숫자를 입력하세요:  11


11 보다 작습니다!


1~20까지의 숫자를 입력하세요:  10


10 보다 작습니다!


1~20까지의 숫자를 입력하세요:  9


9 보다 작습니다!


1~20까지의 숫자를 입력하세요:  5


5 보다 작습니다!


1~20까지의 숫자를 입력하세요:  4


정답입니다!
9 번만에 맞추다니 쩝쩝...


문제 6

In [27]:
t = (10, 20, 30, 40, 50, 60)
t[::-1]

(60, 50, 40, 30, 20, 10)

문제 7

In [44]:
f = open('C:/Users/Conet/number1to10.txt', 'w')
for i in range(1, 11):
    data = "%d\n" % i
    f.write(data)
f.close()

문제 8

In [28]:
import numpy as np

a = np.random.random(10)
a

array([0.97620375, 0.99864207, 0.27800585, 0.01630545, 0.71967406,
       0.91931575, 0.75442624, 0.03007028, 0.42860514, 0.26647723])

In [29]:
a.max()

0.9986420711253938

In [30]:
a.min()

0.01630545239768244

In [31]:
a.mean()

0.5387725828160369

문제 9

In [34]:
a = [[0, 1, 2], [3, 4, 5], [0, 2, 4], [6, 8, 10]]
b = [[0, 1, 2, 0, 2, 4], [3, 4, 5, 6, 8, 10]]

In [39]:
np.concatenate((a[0], a[2]), axis = 0)

array([0, 1, 2, 0, 2, 4])

In [41]:
np.concatenate((a[1], a[3]), axis = 0)

array([ 3,  4,  5,  6,  8, 10])

In [43]:
list(np.concatenate((a[0], a[2]), axis = 0)), list(np.concatenate((a[1], a[3]), axis = 0))

([0, 1, 2, 0, 2, 4], [3, 4, 5, 6, 8, 10])

In [60]:
a = np.array([[0, 1, 2], [3, 4, 5], [0, 2, 4], [6, 8, 10]])
print('a =', a)
a1 = np.append(a[0], a[2])
a2 = np.append(a[1], a[3])
b = np.array([a1, a2])
print('b =', b)

a = [[ 0  1  2]
 [ 3  4  5]
 [ 0  2  4]
 [ 6  8 10]]
b = [[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]]


문제 10

- 결측치와 이상치 여부 확인
- 데이터의 정규성 여부 확인
- 데이터의 본질적인 내용(중심, 산포) 등 확인