퀴즈

#### 1. 

In [1]:
import re
r=re.compile("c.e")
out = r.search('abcdefg')
print(out)
print(out.string)

<re.Match object; span=(2, 5), match='cde'>
abcdefg


#### 2.

In [4]:
import numpy as np
a = np.random.random(20)
print('a = ', a)
print('최댓값: ', a.max())
print('최솟값: ', a.min())
print('평균값: ', a.mean())

a =  [0.85325558 0.44563687 0.36739735 0.4186488  0.09773171 0.16434856
 0.04298631 0.69565719 0.04304782 0.44393614 0.99023984 0.79812181
 0.10561498 0.84648638 0.19367873 0.05916904 0.5992015  0.26735305
 0.36172134 0.38343496]
최댓값:  0.9902398405237834
최솟값:  0.04298631090677785
평균값:  0.4088833981907022


#### 3.

In [7]:
a = np.arange(1, 11)  # range와의 차이; range는 반복가능한 수열이 들어가있는 객체가 들어가있는 반면, arange()는 바로 배열로 출력된다는 특징; 원래는 1차원 배열
a = a[::-1]  # reverse형태로 출력
a = a.reshape(2,5)  # 행이 2개, 열이 5개인 형태로 변환
print(a)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


#### 4.

In [8]:
lyrics = 'Half of my heart is in Havana'
words = lyrics.split()
word_list = []
for w in words:
    word_list.append((w, w.upper()))  # 튜플 형태로 들어가야하므로
    
print(word_list)

[('Half', 'HALF'), ('of', 'OF'), ('my', 'MY'), ('heart', 'HEART'), ('is', 'IS'), ('in', 'IN'), ('Havana', 'HAVANA')]


#### 5. 

In [9]:
import re
r=re.compile("ab{2}c")  # 정규표현식에서 {}가 들어가면 그 앞에 문자가 몇번 반복되는지 설정해줌
print(r.search("abbcdeeee"))

<re.Match object; span=(0, 4), match='abbc'>


#### 6. 

In [10]:
import numpy as np
a = range(1,7)
np.array(a).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### 7. 정규표현식에서 ? (0또는1), * (0이상), + (1이상) 의 의미
특히, 반복과 관련된 정규표현식 알기

#### 8. 

In [13]:
new_list1 = list(range(6,101,6))
print(new_list1)

new_list = list(filter((lambda x: x % 6 == 0), range(1, 101)))  # filter 함수와 lambda 함수 사용; 이때만 true가 나올 것이므로, true가 나오는 값들을 리스트화
print('new_list =', new_list)

[6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]
new_list = [6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]


#### 9. 

In [14]:
import re
r = re.compile("[abc][y]")  # 대괄호에 들어있는 것은, 들어있는 값들 중에 하나를 출력함 (a/b/c)
r.findall("Today is Monday")

['ay', 'ay']

#### 10.

In [15]:
import re
r = re.compile("[^abc]")  # [^abc]대괄호 내에서의 ^의 의미; 시작할 때 문자열 중 a/b/c 제외한 다른 문자 출력, 
                          # ^abc의 의미; 문자열의 시작이 abc로 시작되는 패턴 찾기
r.search("desk")

<re.Match object; span=(0, 1), match='d'>

In [ ]:
shape(2,3,4)  # 2개의 차원에서, 3 * 4 행렬을 의미 (numpy에서)